language: python

sudo: false

branches:
  only:
    - master

python:
  - "3.6"

install: skip

script:
  - echo "skipping tests"

before_deploy:
  - pip install --upgrade wheel
  - python setup.py bdist_wheel

deploy:
  provider: s3
  access_key_id: AKIAJCVE5RZBSCMPSFSQ
  secret_access_key:
    secure: "K+kZd0L1SN4+KFO+dR/xeiJvqV5pUYOEedgWt3U9zkdmcA8irmtYYyf+H8oAs2Qev22snGeh3HlHbOO66X4TIyjZvCYLnF6/nERn6sWyQboE4DlS33Q7DKsJLUcyRxso7Zm2gZkCojoQ+LcTIeYOXgu68grMBts3JDWCi0eAEjsgGwZeORpLkOaNA58KUrTJFzPbmGG5gBz64lcza5xyKe6LU1GOERTH/IhkMYSBNJrBpUb6BhvB2v/AScUBIOqMKoLLC4k8XaK0/K5Nh9xqpXGVOyhxSwou4CsLFTOBwsf17gi3rGiUBLb2LkfWosVwdXyZxlSxVcJ3c9ssxp9mAhy5UaYG87YMEDwJ0VP5srLiBdGYmNWW0GRUlD5r4v4gqlMdEjDLUdaaYMGooeDUl6SgvBd68SSpipduPfhIJBGigNpA1t3tSOzi5sJmKVNB1Ws3rGa1FYO/tOtvE3+qVqtcNohuInwN0q90GQT5ZzML43FRXIcLEd021qZL8CsZ4lxgBKj1EDBIDhY/4wpEpPDHhnzU5E1m7svpCSYzgVbXUuNTr5nldNSx9PhAm691TAERCVWUUkB7qCoLefx1VLTmIaHCHt2dSy/jAMuRr5aN4oLu1TY/7vRFaAbVPiC4TPP9LoF2n20Tcur6WCMS2S+sjt13G47BveZJIZydAls="
  bucket: parsely-artifacts
  skip_cleanup: true
  local_dir: dist
  upload_dir: lib/wheels
  on:
    python: "3.6"
    all_branches: true

after_deploy:
  - 'curl -H "Content-Type: application/json" -H "X-Auth-Token: $RUNDECK_APIKEY" -X POST "https://pypi-webhook.cogtree.com/hooks/wheel-aws-sync"'

env:
  global:
    # RUNDECK_APIKEY
    - secure: "hC116WAvlLQm2zLhqPhe90jAdKtOnimkt3UgoN3f6rqmrBi/j4Jiv7sEV9QVennsCiR89LnKcmqZuxidRJYuMQU5ZBjqhFtx1yh2qgx8DxBJ3dI/pJ+eJLHIh5jPG0/7WD5tNTboKRAqZxze0J76Scazeqowk2R8tI9AVNf8iS+X13/hjweNBNbUe/Oa23/XmYkG0fCw9VMBm253m4K3xG+gWnYTIMH69gnmz4rDkmI3FpFDRFzcxfMfRDgy6R4EkqbCym4YKDI4h0q8NU4h6SeiyOwUMXEeE/e2dage0m2YYm0NlkBy7EFLjqE+HCzh2nejrBkHMYvTV12uTyRC/LZomFFNhwTK1uONJUxdGm8Y+qc9CVFmpvU0KT5NxQpipsYWwuU4DS5yAa5F9U7h/pePq6aknRvLj7cMnflYm3FZ9xwOIGrcaNFTPDoeiAZ/XBFcS/253fsRzauAatpiSXhHtaTOLj4dKKFzCKyNFGOq9CKVgFcC6ob6ynR4mMpC6zo8NzqBBPQBYHX3AW2cgnwyjr+q2rxT6r3ZXkuDT+J2G6i7Ns19X8AQUG5F9JwSbLpYG1T62IBrxCz25yTAjKHKxbRLrqIAsLHBpbPykDT/0AeE28Q9bcgnuRs7xDtmNgLehfyf3XmAwJixxdXE1bF5jrEJYNm3nn6xaGeYHiI="
