language: python
source_key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBc1FTTG5pYjcyZVU3WlRlUXl0ZTcvR2dHVGpDKzlOaURJMGg1V1phVmVrd0libzJ4CnVzNmVsOHJYTlBrRi9rbXFsd0pkeGhGQ3V0NFVIeHF6dW01dW5zOWdHTHQ2WVRNeWU1NjVlRUVDeHBXM1ZWVnIKckQ4bUh2VGt3NHlVTDB0dnJYeVQvdjRNV1F0VWNDSWVGa3U5alZYTE4xTnZHR3hHeExrOFhFMlNWWDVvR3hEegpZVTZDenNhV1ArcnZ4d2owZHppQVhnSEg4NGxxSFBqK2RDdG5SSkdQWjdNanJ3Zm51NWF0d3I1V0I5VjhvUlM2CmVISVJLWTZ3Umc5L1RFOGgrQytJWDdJOGFMVEpoQWt6NjFWVjc2dk0yTUVya2NzQ1VhS05oclNVQlBpYnlaRSsKdEFRemNDN0tuamJBaGV4dWdvOXN4T0tZQS9XUHlOMTg0aVZUNFFJREFRQUJBb0lCQVFDYVMvRDdBTllFWHloLwptSWlRRnEzWVhFQXF4WmlkU1dBOVQvM2Vsa0JpNG9WeS8vVk1kSytPZGhOU0xFSUtIZUloVU1HMlZQTktlU3NtCjFacVZ4WTZNeFF2cFl2bFFZbFQ5cGlQYWF5aGxPcmtjRzZJSCtOOWNtbkFROTZkdTloMDVKbDdHSkdGVStHZzQKZWJTcUVJai8raWx4Wnp0dUdXc3lMSmd0aUx3bDRkN1VtcjhPTlRwWTNGNHM1TUVYTmwwWDdXRjV2THNUd3NyegpEZVU1ZEU5UkpDSHRYVWxwVjNaYW9PN2QrWWVnZ3JRNmc3L3llcG9remx1ajJRMjh3T1ovZkxVeEdLS25rNVU2CjZhcklhN2hvYVNQSGtvb1FhRkgxN2RtdWJyWHFqcUg1VGtIZ2U0d0xod25NSTVPbEptcXE0MGVWREpRNWp5dVIKN1RodnR1ZVZBb0dCQU5xY0U4aXdJb1hqQjlnTXpTdHpiTU9VaHJaZlUzb1ZXU1pnRXBLTjJnNi9NanV6eER1Wgo2MEYvTmp5Y05yL0ZjQlZwVzJxUmdyMlhzMFlWVnFiZ2ZPak54LzN0cnpSRFpJVlFVRzVJeEJUY1UveHhOQ1FUCnUyNW5lMXdpalIrWUoyYUJzZmdFc00xa0pDRXQraVdycmxaMVNxYkZGWlprVnNZYzNZVFIyaGYzQW9HQkFNOUwKV09Bcnk0emJ6QXhQTHdDZnZoclY4bitvSnkreFJINjBjSno1VTFHUmZQRzVTWnh5Y2xTaldvR2pVMjRCMm42UQpsZTNzbU01RXgzdm9xcit2U1NyaHRmTG1FbW5CRXBBWXlOYlZrV1g3MlZ5T25rbnN5UnNxckRQZ2pBMDhNakFQCmFQUHYzWEQ2RWlQT2h6aWZGbm1HZ1JQWlFFYVVCVWdEKy9GdFR1em5Bb0dBYUFyMlk0Sm91OTRFZ3EvOUNkd0MKZk1iNG9sMldKamw0MTRuTDdSSTBJT2FnYXNldzhramNMYXowekQzdzFLNk1ITFNxL0hwS2hoOW9CRWZ0bUxpbwoya2Z1RWcySVlGQmV6QkFnWjR5Y1BlMXF6MisxU0NKWUIwQ2E5b3UvTExWR3MwT3d4d0M4Z05SVFdiTS9KYVNpCjhhVWJKV29SVHlWc0l4ZmoyZTNpWlpzQ2dZRUFybzZoV2F3bmJRY05qWFFFZlg4RzQ2d3oxMEd2TmQ4TmNiRGEKZjZVSWYxQ0hLVHBBL1dmMlZNVjJDbUtSZDdwQjFvQkVjS1RpakJlbzcvT2VEV282cjh4L25mb1ZtVTVISm1abwpnVmc0WnV1c1B0K3Q5VXhha1BEZkw1UXYrMWtzWGdJcisvYUp2NEFsVkZldTBJUk90YWtJK3NEZitrN2RINmFUCk90czBNaE1DZ1lFQWlZTHNvSDRFZGFJMHBBYkhJRWt6eWE4Ny9PalBidkZjamdzbEdsTmFKTzJqSWpxWGpvT1AKM2tnaTZDT294UDh2VVM1UzdwNG4wSllwc3Z1RHIzM3g2aTVBVWdiOUpVLzYwSkt1clpxb1ZHUHg2dXVQbmdUbgpkSHA0VGVocXBqMlN3MEdveVNoWFZaVFJkcDZYc3NwSlVtdm1YQ29DTitGQkdVWUlQNmUwcWNJPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="

sudo: false

branches:
  only:
    - master

python:
  - "3.6"

install: skip

before_deploy:
  - pip install --upgrade wheel
  - python setup.py bdist_wheel

deploy:
  provider: s3
  access_key_id: AKIAJCVE5RZBSCMPSFSQ
  secret_access_key:
    secure: "kEuoT/D1yUdZuJpSgKcEyxoh3w3lobQIXUOErIF/y26wrLepH0yqMahQ6Exlk22grsT0LrgfdvfWpADalo/KdxaopcNG2Om8gC/iIFFzZxl9FJ84DQP9O4zBMna0+OOEgmhv15U5Gg2M6cWBytoVeL/VKeuO9BwBZHOfbNdHlv8="
  bucket: parsely-artifacts
  skip_cleanup: true
  local_dir: dist
  upload_dir: lib/wheels
  on:
    python: "3.6"
    all_branches: true

after_deploy:
  - 'curl -H "Content-Type: application/json" -H "X-Auth-Token: $RUNDECK_APIKEY" -X POST "https://pypi-webhook.cogtree.com/hooks/wheel-aws-sync"'

env:
  global:
    # RUNDECK_APIKEY
    - secure: "dqQQRV2Oj/X54aaDSQI1sH7MBMYiKSSHn8jLuywC8Fad0muctPsUL852w+NHULOary9XWuYsQbbRK9hQVeAR9ujSJ99nEvmB6DpRtY+QdpUPw7f9M4f6FYzQvBADEGpwT3us5qScJkXjhDEx+HIqguYOo1/SxbZEqVFaIyC8iAg="
    # PIP_EXTRA_INDEX_URL
    #- secure: "kxKFEWZfsT+VrVYUaePoPCH48WAWIaoHVxDNUJWL0UzA2q6zdMmn6ekUMSZ8AlHb3/qD08lkT2K/lKEgiwM9t4mTVVs51N5okmizRfpYyHB9JtLvOIPBlBSmnMlgVjpOT0fANNuAnh3o+RPX82jW+Jxb4eNfdxdpF5yfbTsvYZA=" 
